feat(adaptive): add adaptive for subscribe block
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #27
Opened 2023-09-18 12:21 UTC by AleksandrDronov

2023-09-18 20:33 UTC, elrouss requested changes
Получилась аккуратная разметка, очень хорошо. Все плавно и красиво сжимается!
Несколько замечаний оставил в комментариях, где главный - по введению дополнительного брейкпоинта, который мы не согласовывали. Уверен, что у тебя получится справиться с разметкой без него

Также в идеале хотелось бы прописать еще это свойство для пунктов причин регистрации ->  в таком случае все встанет идеально по PP :)
<img width="173" alt="Снимок экрана 2023-09-18 в 23 29 20" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/8039cf34-fbaa-4412-93f9-16bcf6a73a0c">

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
> +    margin-left: 48px;
Вынести в переменную `$indent-section-sides-desktop`

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
> +    margin-right: 48px;
Вынести в переменную `$indent-section-sides-desktop`

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
>    border: 1px solid var(--stroke, rgba(189, 189, 189, 0.36));
Вспомнил недавно, что в SCSS (и вроде бы в CSS) есть изящный способ рисования с помощью rgba: `rgba($color: <переменная>, $alpha: <прозрачность>)`. Давай здесь сделаем так?

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
> +    margin-top: 28px;
Вынести так: `calc($indent-section-top-side-desktop-small / 2)`

2023-09-18 20:33 UTC, elrouss commented on src/assets/styles/abstracts/variables/media-queries.scss
> +$media-desktop-main-page-subscribe-block: 1600px;
В `1535px` не вписываешься? Можно начать, например, плавно уменьшать margin с 1919px, если не хватает места. Но в целом, как я посмотрел, это дает тебе сравнительно небольшое преимущество в 10-12px. Лучше тогда пускай один спускается на строчку, как есть. Брейкпоинты должны быть одинаковые, и все должно меняться по общим принципам. Ради одного марджина не стоит вводить дополнительный брейкпоинт

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
> +      margin: 50px 0 50px 56px;
Прокомментировал выше

2023-09-18 20:33 UTC, elrouss commented on src/components/subscribe-block/styles.module.scss
> +    @media screen and (max-width: calc($media-desktop-main-page-subscribe-block - 1px)) {
Прокомментировал выше.

Можно попробовать поиграть с `gap` и отказаться от абсолютных величин в пользу относительных

2023-09-19 07:45 UTC, AleksandrDronov commented
Исправил

2023-09-19 08:21 UTC, elrouss approved these changes
Все супер)

Обязательно возьми заметку на будущее с rgba в scss/css :)

2023-09-19 08:38 UTC, merged