feat(news-preview-page): create adaptive 1280
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #28
Opened 2023-09-18 19:54 UTC by elrouss

Ответвился от main, чтобы видеть header и footer; реализовал страницу с карточками превью новостей.
1) Проверь, пожалуйста, мое решение с кнопкой "Наверх". Мне кажется, что так будет симпатичнее, хотя не очень красиво, что она скачет вниз при нажатии на "Еще". Но здесь, думаю, дело в логике. Если бы карточки у нас подгружались плавно просто при скролле вниз, то кнопка бы не прыгала.
2) Если все ок, влей в adaptive-main-1280, и можно в принципе вливать в adaptive (сейчас гляну твой коммит).

2023-09-19 09:58 UTC, AleksandrDronov requested changes
Классно сделал кнопку

2023-09-19 09:58 UTC, AleksandrDronov commented on src/components/header/menu/menu.module.scss
> +    &::after {
Тут можно обойтись без псевдоэлемента, просто при ховере показывать нижний бордер.

2023-09-19 18:48 UTC, elrouss commented
Добавил нижний паддинг, чтобы можно было выбрать меню, включая то место, где рисуем нижнее подчеркивание; все делать нужно через псевдоэлемент, чтобы реализовать плавную анимацию появления/скрытия (согласовано с дизайнерами)

2023-09-20 02:38 UTC, elrouss commented
И еще сделал адаптив ленты статей. Можешь, пожалуйста, влить сюда же в этот реквест от себя изменения по табам со специализациями? Их должно быть на 1 штуку меньше. И мы, может, наконец-то получим бобы :)

2023-09-20 07:06 UTC, AleksandrDronov approved these changes

2023-09-20 07:32 UTC, merged