feat: add search
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #4
Opened 2023-08-30 13:00 UTC by AleksandrDronov

2023-08-31 16:18 UTC, elrouss requested changes
Круто, проделана большая работа! Однако есть что поправить. Также обрати внимание на отступы внизу блока

<img width="692" alt="Снимок экрана 2023-08-31 в 19 17 24" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/a6453242-6841-4eb3-b73a-ed11107684b1">

2023-08-31 16:18 UTC, elrouss commented on src/components/header/search/index.tsx
>        <input
Не смог найти по коду, где можно было бы поставить `cursor: pointer` у крестика, который очищает содержимое внутри `input`. Предлагаю его добавить. Кроме того, крестик сделан почему-то через `div`, а не через `button`. Это плохо для ЛОВ

2023-08-31 16:18 UTC, elrouss commented on src/pages/search-page/search-page.module.scss
> +.crumbs {
Точно есть такой класс на странице?

2023-08-31 16:18 UTC, elrouss commented on src/pages/search-page/search-page.module.scss
> +.description {
Точно есть такой класс на странице?

2023-08-31 16:18 UTC, elrouss commented on src/pages/search-page/search-page.tsx
> +  const toggleButtonVisible = () => {
Давай вынесем в отдельную универсальную функцию? Сейчас она дублируется на 4 страницах

2023-08-31 16:18 UTC, elrouss commented on src/pages/search-page/search-page.tsx
> +                  <br />
Не самый удачный тег для переноса строки: его используют обычно для поэм. Попробуй два `p`

2023-08-31 18:15 UTC, AleksandrDronov commented on src/components/cards/card-search/card-search.module.scss
> +  max-width: 1054px;
Посмотрел, для другой карточки нет переменной. Либо везде делаем либо везде не делаем.

2023-08-31 18:22 UTC, AleksandrDronov commented on src/components/cards/card-search/card-search.module.scss
Думал над этим. Решил вынести в отдельный компонент. Решил, что карточка становится слишком сложным мудреным компонентом. Хотя сейчас смотрю, может и нет. Предлагаю отрефакторить уже после презентации. Завтра слишком мало времени у меня, могу не успеть.

2023-08-31 18:33 UTC, AleksandrDronov commented on src/components/cards/card-search/card-search.tsx
> +            {converMdToHTML(annotation, true)}
Так как раз у нас аннотация прилетает в MD разметке. Мы конвектируем в html.  Это сделано и в другой карточке. Если на стороне админке, захотят, к примеру, выделить слово жирным в MD разметке, то у нас оно тоже станет жирным.

2023-09-01 04:04 UTC, elrouss commented on src/components/cards/card-search/card-search.module.scss
> +  max-width: 1054px;
Давай везде вынесем? Я где-то использовал переменную `$wrapper-authors-desktop: 1054px`

2023-09-01 04:05 UTC, elrouss commented on src/components/cards/card-search/card-search.module.scss
Окей. Главное, не забыть

2023-09-01 04:06 UTC, elrouss commented
И проверь еще на PP состояние в случае отсутствия выдач по запросу

2023-09-01 11:14 UTC, AleksandrDronov commented on src/pages/search-page/search-page.module.scss
> +.description {
есть

2023-09-01 13:14 UTC, elrouss approved these changes
Отличный хук получился. Вроде бы ничего не сломалось))

Пара совсем мелких замечаний, но аппрувлю, чтобы не тянуть. Поправишь перед мерджем?

2023-09-01 13:14 UTC, elrouss commented on src/components/cards/card-search/card-search.module.scss
> +  min-width: 200px;
Добавить `max-width: 200px` и добавить свойство `width: 100%`.

Убрать `width: 200px` и `min-width: 200px;`

2023-09-01 13:14 UTC, elrouss commented on src/components/cards/card-search/card-search.tsx
> +            {converMdToHTML(annotation, true)}
Хм, увидел, что Полина переделала. Обычно в аннотациях не выделяют текст жирным. Но ладно. Плохо, конечно, что в `span` содержится огромный текст, который еще и внутри `p`. Ладно, к 3-му релизу по возможности поправим

2023-09-01 13:14 UTC, elrouss commented on src/components/header/search/index.tsx
> +      navigate(`/search/${value}`);
`search` уже вынесен в объекте `api` -> обратиться к нему через ключ

2023-09-01 13:14 UTC, elrouss commented on src/hooks/useToggleButtonVisible.ts
> +export const useToggleButtonVisible = (heightTop = 1250) => {
"Магическое" значение -> вынести по крайней мере в глобальную переменную

2023-09-01 13:40 UTC, merged