feat: adapt news and article pages for 1280
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #46
Opened 2023-09-22 10:50 UTC by SirojaSB

2023-09-22 12:04 UTC, elrouss requested changes
Отличная работа, но зачем ты сделал новый тип карточки? Все требуемые стили прописаны в дефолтном. Надо убрать :)

Поправь также, пожалуйста, маргин (мне кажется, что там лишний в 8px) и измени "Е" на "Ё" (по макету)

<img width="400" alt="Снимок экрана 2023-09-22 в 14 42 21" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/4b6cfa5a-00c0-4a51-a813-1370ef9c2bde">
<img width="429" alt="Снимок экрана 2023-09-22 в 14 42 36" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/f725ab59-8aae-4047-a9bc-d6572a79e6cb">
<img width="261" alt="Снимок экрана 2023-09-22 в 14 45 46" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/ec5e1f72-8d23-4196-9c26-e6462a77ec52">

2023-09-22 14:25 UTC, SirojaSB commented on src/components/cards/article-preview/article-preview.module.scss
> +  &--fullPageArticle {
Карточка на 1280 на странице articles preview и на article по разному выглядит, поэтому еще один тип сделал

2023-09-23 12:42 UTC, elrouss commented on src/components/cards/article-preview/article-preview.module.scss
> +  &--fullPageArticle {
Увидел. Тогда этот и аналогичный вопрос отпадают

2023-09-23 17:06 UTC, AleksandrDronov commented
От себя добавлю. На брейкпоинте 1535 контент страницы резко перескакивает в центр. Лучше воспользоваться формулой, чтобы не было резкого перелома

2023-09-23 17:11 UTC, elrouss commented
В данном кейсе на самом деле это особо без разницы

2023-09-23 19:02 UTC, AleksandrDronov commented
> В данном кейсе на самом деле это особо без разницы

На всех остальных страницах у нас такого не наблюдается. Мы меняем отступы по формуле.

2023-09-23 19:05 UTC, elrouss commented
Повторюсь, что в данном кейсе это не особо критично, так как здесь - огромные отступы от центрального контейнера до краев хедера и визуально это никак особо не влияет

2023-09-25 15:52 UTC, elrouss approved these changes
Отличная работа!

2023-09-25 15:52 UTC, merged