feat(adaptive): add adaptive for search page
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #47
Opened 2023-09-23 16:05 UTC by AleksandrDronov

2023-09-25 18:45 UTC, elrouss requested changes
Очень хороший коммит, однако, есть пара моментов, которые можно улучшить (на твое усмотрение).

Из критичного - расхождение с Pixel Perfect. Высота карточки должна быть на `4px` выше (т. е. не `144px`, а `148px`). К концу ряда это расхождение нарастает и превращается в то, что видим на скрине. Исправление сделает все идеальным на 1920 и 1280. Больше ничего не меняй (в частности, подвал): мне кажется, что дизайнеры допустили там ошибку с нижним отступом на 1280. Оставил им комментарий в Фигме
<img width="482" alt="Снимок экрана 2023-09-25 в 21 25 30" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/b91c23ac-1c9f-46bc-9b39-ed46df02237b">
<img width="231" alt="Снимок экрана 2023-09-25 в 21 26 16" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/ec78ef24-cc58-4e41-9181-e39ad6125aa1">
шоте

2023-09-26 06:25 UTC, AleksandrDronov commented on src/pages/search-page/search-page.tsx
> +          {windowDimensions >= desktopMedium ? (
Решил не переделывать, так как в другом месте написано так же. В угоду одноообразия.

2023-09-26 06:26 UTC, AleksandrDronov commented
Дизайнеры в тихоря изменили высоту карточки, а я и не проверил :).

2023-09-26 08:03 UTC, elrouss approved these changes
Отличная работа!

2023-09-26 08:04 UTC, merged