Feat/adaptive search page 768 375
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #68
Opened 2023-10-02 12:13 UTC by AleksandrDronov

2023-10-02 19:31 UTC, elrouss requested changes
Проделана большая работа, но есть, что поправить (отметил в комментариях). Плюс обрати внимание на необходимость проверки по PP (напр., где-то слетают размеры фотографий, не выставлен нужный интерлиньяж или не тот отступ между карточками)
<img width="330" alt="Снимок экрана 2023-10-02 в 22 19 15" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/0f5594d0-1d7c-4ffd-a5ab-3e0c85f20f24">
<img width="308" alt="Снимок экрана 2023-10-02 в 22 14 39" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/be4cfc6c-3008-4bf4-91bc-ae42746459a5">
<img width="463" alt="Снимок экрана 2023-10-02 в 22 14 49" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/f5286b30-f37f-45d8-8bc3-17d0f5d18079">

<img width="294" alt="Снимок экрана 2023-10-02 в 22 13 07" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/544c2805-f0e2-460d-9dcc-0bc72e621bb7">

2023-10-02 19:31 UTC, elrouss commented on src/components/cards/card-search/card-search.module.scss
> +    line-height: calc-fluid-element(
Меняем резко на 1024px

2023-10-02 19:31 UTC, elrouss commented on src/pages/search-page/search-page.module.scss
> +    line-height: calc-fluid-element(
Меняем резко на 1024

2023-10-02 19:31 UTC, elrouss commented on src/pages/search-page/search-page.module.scss
> +    > article > a > div {
Почему таким образом, если это у нас отдельный компонент карточки? Его и модифицируем

2023-10-02 19:31 UTC, elrouss commented on src/pages/search-page/search-page.module.scss
> +      > img {
Почему таким образом, если это у нас отдельный компонент карточки? Его и модифицируем

2023-10-03 18:04 UTC, AleksandrDronov commented
Исправил

2023-10-14 06:02 UTC, elrouss requested changes
Определенно стало лучше, но есть, что еще поправить по PP. Обрати внимание на отступы до подвала (дизайнеры скорректировали). Также gap между карточками не стоит уменьшать по формуле -> меняем резко при перестройке сетки. Обрати также внимание на крайнее нижнее положение кнопки "Наверх" на мобиле (по аналогии с лентой новостей)

<img width="917" alt="Снимок экрана 2023-10-14 в 08 47 47" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/fa953b81-57d1-457f-967a-6e96ee19c535">
<img width="864" alt="Снимок экрана 2023-10-14 в 08 50 24" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/c2019e73-6fd1-484b-ab7d-656c8903f918">
<img width="225" alt="Снимок экрана 2023-10-14 в 08 51 12" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/63ab6676-1f06-4c8e-abef-f930fa8a9237">
<img width="278" alt="Снимок экрана 2023-10-14 в 08 58 35" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/89037518-c179-4cd9-818d-07e7a0c002dd">
<img width="449" alt="Снимок экрана 2023-10-14 в 09 01 14" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/13b9df27-4770-4e46-b793-e1ae7c80d425">

2023-10-14 11:59 UTC, AleksandrDronov commented
Изменил поведение кнопки по согласованию с дизанейрами. Теперь на планшете и меньше она fixed к низу окна браузера.  Исправил нижние отступы до футера.

2023-10-15 03:44 UTC, elrouss requested changes
Убрать нижний отступ на планшете, и ПР будет принят :))

<img width="535" alt="Снимок экрана 2023-10-15 в 06 39 29" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/ee468364-f985-44b5-8aab-ea6cb795095f">

2023-10-15 05:51 UTC, AleksandrDronov commented
Поправил. Ох уж эти отступы.

2023-10-15 05:57 UTC, elrouss commented
Да не говори

2023-10-15 05:57 UTC, elrouss approved these changes
Все хорошо :)

2023-10-15 05:57 UTC, merged