feat(adaptive): adaptive for slider and modal 768 375
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #70
Opened 2023-10-07 16:47 UTC by AleksandrDronov

Слайдер и модалка с фильтрами.

2023-10-12 18:44 UTC, elrouss requested changes
Отлично сделано, но обрати внимание на отступ до скроллбара, а также ширину последнего, на мобиле он меняется с 10 до 6 (возможно, стоит это сделать уже на альбомной ориентации планшета). Не уверен, что при разворачивании второго списка скроллбар должен появляться на высоту двух контейнеров: логичнее - около того контейнера, который развернут

<img width="316" alt="Снимок экрана 2023-10-12 в 21 33 14" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/852df117-e993-4868-8826-aa3d6f407b1a">
<img width="200" alt="Снимок экрана 2023-10-12 в 21 36 20" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/b92dece4-9f78-4ca1-9f99-f4368c39161c">
<img width="231" alt="Снимок экрана 2023-10-12 в 21 36 44" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/d0a2d627-16d0-481e-9fc3-e835fa500d08">

2023-10-14 14:56 UTC, AleksandrDronov commented
Толщину скролла поправил. 
По поводу контейнера скролла:
Если делать как ты говоришь, отдельно на теги, то будет скролится только контейнер тегов.  То есть половина модалки. Как то странно будет.

2023-10-14 15:29 UTC, elrouss commented
Все, я сообразил, как оно работает. Нормально смотрится, просто когда скроллы были прижаты к фильтрам - не очень выглядело.

А странного ничего нет, ведь на десктопе у нас и так на каждый контейнер свой скроллбар)

2023-10-14 15:38 UTC, elrouss approved these changes
Все вроде бы хорошо, молодец!

Единственное, все равно не нравится отрисовка табов: тут нужна математическая логика, которая бы рассчитывала размеры каждой ячейки и в зависимости от этого отрисовывала то или иное количество табов.

Но не будем на данном этапе особо на этом зацикливаться. Главное, что логика работает и более-менее красиво :)

2023-10-14 15:39 UTC, merged