feat(adaptive): adaptive for auth
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #91
Opened 2023-10-19 14:10 UTC by AleksandrDronov

Страница регистрации

2023-10-21 14:40 UTC, AleksandrDronov commented
Закончил авторизация и регистрация

2023-10-25 18:46 UTC, elrouss requested changes
Сделано крайне неплохо: из существенного - поправить верстку (на скриншоте)

<img width="796" alt="Снимок экрана 2023-10-23 в 19 44 38" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/108838349/9c9d2b0c-1f35-4fb1-a90b-12f4158a91bd">

2023-10-26 07:15 UTC, AleksandrDronov commented on src/shared/buttons/button/button.module.scss
> +    padding: 12px 38px;
исправлено

2023-10-26 07:24 UTC, elrouss approved these changes
Вроде бы все хорошо. Check :)

2023-10-26 07:24 UTC, merged