Feat/adaptive personal account
Medical-Information-Portal-Stethoscope/medical-information-frontend pull request #95
Opened 2023-10-21 21:21 UTC by elrouss

1) Не делал кнопку "Еще" в галерее избранных (следует сначала закончить фичу добавления в избранное);
2) У дизайнеров немного скачут отступы до подвала и между сайдбаром и секциями на планшете/мобиле -> не акцентировал внимание на этом;
3) Отдельной таской стоит проработать кнопку "Наверх" (высчитывание ее появления на маленьких экранах).

2023-10-22 16:13 UTC, AleksandrDronov requested changes
Все отлично, хорошая верста по PP. Пару замечаний.
1. Хедер для планшета надо поправить. 

<img width="449" alt="image" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/93670312/429731bb-f8cb-4b92-8090-2a344b523c89">

2. Избранное и публикация статьи. Для планшета и мобилы отсутствует этот блок 

<img width="335" alt="image" src="https://github.com/Medical-Information-Portal-Stethoscope/medical-information-frontend/assets/93670312/cefca68c-86e5-485d-a1e7-4648f22511d2">

2023-10-23 07:53 UTC, elrouss commented
1. Делает Сергей;
2. Выяснили, что был какой-то баг: все работает :)

2023-10-23 16:18 UTC, elrouss commented
Внес изменения в верстку (прежде всего, в инпуты), следуя изменениям в макете

2023-10-24 06:20 UTC, AleksandrDronov approved these changes
Все вроде гуд

2023-10-24 06:21 UTC, merged